import { ArrowUpCircleIcon } from "@heroicons/react/24/solid";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(26,26,26)] text-white overflow-x-hidden overflow-y-scroll snap-y snap-mandatory z-0 h-screen scroll-smooth scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-orange-400">
      <span id="backtotop"></span>
      <Head>
        <title>Sharull | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      <section id="experience" className="snap-center">
        <WorkExperience />
      </section>
      <section id="skills" className="snap-start">
        <Skills />
      </section>
      <section id="projects" className="snap-start">
        <Projects />
      </section>
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>
      <div className="absolute bottom-10 right-10">
        <Link href="#backtotop">
          <ArrowUpCircleIcon className="w-10 h-10" />
        </Link>
      </div>
    </div>
  );
};

export default Home;
